# This file stores configurations for your Shopify app.
# It must exist at the root of your app.

name = "theme-extension-playground"
client_id = "aa2e8ef1ecccc3b3abdae1a3b8a77ae6"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home" ]

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""
