# This file stores configurations for your Shopify app.
# It must exist at the root of your app.

name = "shopify-app-playground"
client_id = "aa2e8ef1ecccc3b3abdae1a3b8a77ae6"
application_url = "https://shopify-app-playground.pavel-usanli.online"
embedded = true

[auth]
redirect_urls = [ "https://shopify-app-playground.pavel-usanli.online/api/auth" ]

[webhooks]
api_version = "2025-10"

[access_scopes]
scopes = "write_products"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
